# Generated by Django 2.0.3 on 2018-04-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='课程号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('credit', models.FloatField(verbose_name='学分')),
                ('capacity', models.IntegerField(verbose_name='容量')),
                ('classroom', models.CharField(max_length=20, null=True, verbose_name='教室')),
                ('assessment', models.CharField(max_length=20, null=True, verbose_name='考核方式')),
            ],
        ),
    ]
