# Generated by Django 2.0 on 2018-06-02 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='authentication.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(0, '春'), (1, '夏'), (2, '春夏'), (3, '秋'), (4, '秋冬'), (5, '短')], default=0, verbose_name='开课学期'),
        ),
    ]
