# Generated by Django 2.0.3 on 2018-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='id_number',
            field=models.CharField(default='null', max_length=18, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='null', max_length=10, primary_key=True, serialize=False, verbose_name='课号'),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, '不通过'), (1, '待审批'), (2, '已通过')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户名'),
        ),
    ]
