# Generated by Django 2.0.3 on 2018-04-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180428_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_number',
            field=models.CharField(default='null', max_length=18, unique=True, verbose_name='身份证号'),
        ),
    ]
