# Generated by Django 2.0.3 on 2018-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180428_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id_number',
        ),
        migrations.AddField(
            model_name='people',
            name='id_number',
            field=models.CharField(default='null', max_length=18, unique=True, verbose_name='身份证号'),
        ),
    ]
