INSERT INTO "auth_permission" VALUES ('1', '1', 'add_faculty_course', 'Can add faculty_ course');
INSERT INTO "auth_permission" VALUES ('2', '1', 'change_faculty_course', 'Can change faculty_ course');
INSERT INTO "auth_permission" VALUES ('3', '1', 'delete_faculty_course', 'Can delete faculty_ course');
INSERT INTO "auth_permission" VALUES ('4', '2', 'add_people', 'Can add people');
INSERT INTO "auth_permission" VALUES ('5', '2', 'change_people', 'Can change people');
INSERT INTO "auth_permission" VALUES ('6', '2', 'delete_people', 'Can delete people');
INSERT INTO "auth_permission" VALUES ('7', '3', 'add_major_class', 'Can add major_ class');
INSERT INTO "auth_permission" VALUES ('8', '3', 'change_major_class', 'Can change major_ class');
INSERT INTO "auth_permission" VALUES ('9', '3', 'delete_major_class', 'Can delete major_ class');
INSERT INTO "auth_permission" VALUES ('10', '4', 'add_major', 'Can add major');
INSERT INTO "auth_permission" VALUES ('11', '4', 'change_major', 'Can change major');
INSERT INTO "auth_permission" VALUES ('12', '4', 'delete_major', 'Can delete major');
INSERT INTO "auth_permission" VALUES ('13', '5', 'add_staff', 'Can add staff');
INSERT INTO "auth_permission" VALUES ('14', '5', 'change_staff', 'Can change staff');
INSERT INTO "auth_permission" VALUES ('15', '5', 'delete_staff', 'Can delete staff');
INSERT INTO "auth_permission" VALUES ('16', '6', 'add_admin', 'Can add admin');
INSERT INTO "auth_permission" VALUES ('17', '6', 'change_admin', 'Can change admin');
INSERT INTO "auth_permission" VALUES ('18', '6', 'delete_admin', 'Can delete admin');
INSERT INTO "auth_permission" VALUES ('19', '7', 'add_student', 'Can add student');
INSERT INTO "auth_permission" VALUES ('20', '7', 'change_student', 'Can change student');
INSERT INTO "auth_permission" VALUES ('21', '7', 'delete_student', 'Can delete student');
INSERT INTO "auth_permission" VALUES ('22', '8', 'add_department', 'Can add department');
INSERT INTO "auth_permission" VALUES ('23', '8', 'change_department', 'Can change department');
INSERT INTO "auth_permission" VALUES ('24', '8', 'delete_department', 'Can delete department');
INSERT INTO "auth_permission" VALUES ('25', '9', 'add_account', 'Can add account');
INSERT INTO "auth_permission" VALUES ('26', '9', 'change_account', 'Can change account');
INSERT INTO "auth_permission" VALUES ('27', '9', 'delete_account', 'Can delete account');
INSERT INTO "auth_permission" VALUES ('28', '10', 'add_course', 'Can add course');
INSERT INTO "auth_permission" VALUES ('29', '10', 'change_course', 'Can change course');
INSERT INTO "auth_permission" VALUES ('30', '10', 'delete_course', 'Can delete course');
INSERT INTO "auth_permission" VALUES ('31', '11', 'add_faculty', 'Can add faculty');
INSERT INTO "auth_permission" VALUES ('32', '11', 'change_faculty', 'Can change faculty');
INSERT INTO "auth_permission" VALUES ('33', '11', 'delete_faculty', 'Can delete faculty');
INSERT INTO "auth_permission" VALUES ('34', '12', 'add_logentry', 'Can add log entry');
INSERT INTO "auth_permission" VALUES ('35', '12', 'change_logentry', 'Can change log entry');
INSERT INTO "auth_permission" VALUES ('36', '12', 'delete_logentry', 'Can delete log entry');
INSERT INTO "auth_permission" VALUES ('37', '13', 'add_group', 'Can add group');
INSERT INTO "auth_permission" VALUES ('38', '13', 'change_group', 'Can change group');
INSERT INTO "auth_permission" VALUES ('39', '13', 'delete_group', 'Can delete group');
INSERT INTO "auth_permission" VALUES ('40', '14', 'add_permission', 'Can add permission');
INSERT INTO "auth_permission" VALUES ('41', '14', 'change_permission', 'Can change permission');
INSERT INTO "auth_permission" VALUES ('42', '14', 'delete_permission', 'Can delete permission');
INSERT INTO "auth_permission" VALUES ('43', '15', 'add_contenttype', 'Can add content type');
INSERT INTO "auth_permission" VALUES ('44', '15', 'change_contenttype', 'Can change content type');
INSERT INTO "auth_permission" VALUES ('45', '15', 'delete_contenttype', 'Can delete content type');
INSERT INTO "auth_permission" VALUES ('46', '16', 'add_session', 'Can add session');
INSERT INTO "auth_permission" VALUES ('47', '16', 'change_session', 'Can change session');
INSERT INTO "auth_permission" VALUES ('48', '16', 'delete_session', 'Can delete session');
INSERT INTO "auth_permission" VALUES ('49', '17', 'add_token', 'Can add Token');
INSERT INTO "auth_permission" VALUES ('50', '17', 'change_token', 'Can change Token');
INSERT INTO "auth_permission" VALUES ('51', '17', 'delete_token', 'Can delete Token');
