# Generated by Django 2.0 on 2018-06-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('title', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='标题')),
                ('apply_des', models.CharField(max_length=32, verbose_name='申请说明')),
                ('state', models.IntegerField(default=0, verbose_name='申请状态')),
                ('create_time', models.DateField(auto_now=True, verbose_name='申请时间')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_location', models.CharField(max_length=50, unique=True, verbose_name='地点')),
                ('classroom_capacity', models.IntegerField(verbose_name='容量')),
            ],
        ),
        migrations.CreateModel(
            name='course_select_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_state', models.PositiveSmallIntegerField(choices=[(0, 'unscreened'), (1, 'passed'), (2, 'unpassed')], default=0)),
                ('date_selected', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_teacher_time_classroom_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5, verbose_name='时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_rid', to='score_management.ClassRoom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cid', to='authentication.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_tid', to='authentication.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, null=True, verbose_name='分数')),
                ('test_date', models.DateField(auto_now=True, verbose_name='考试时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Score_Relation',
            fields=[
                ('course_select_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='score_management.course_select_relation')),
                ('score', models.IntegerField(default=0, null=True, verbose_name='分数')),
                ('test_date', models.DateField(default='2018-07-01', verbose_name='考试时间')),
                ('modify_state', models.BooleanField(default=False, verbose_name='上传状态')),
            ],
        ),
        migrations.AddField(
            model_name='course_select_relation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecting_cid', to='score_management.course_teacher_time_classroom_relation'),
        ),
        migrations.AddField(
            model_name='course_select_relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='course_select_relation',
            unique_together={('student', 'course')},
        ),
    ]
