# Generated by Django 2.0 on 2018-06-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('score_management', '0002_auto_20180618_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalysis',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Student')),
                ('rank', models.IntegerField(null=True, verbose_name='排名')),
            ],
            bases=('authentication.student',),
        ),
    ]
