# Generated by Django 2.0.5 on 2018-06-04 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('online_testing', '0003_auto_20180603_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 5, 56, 22, 210351, tzinfo=utc), verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 5, 56, 22, 210351, tzinfo=utc), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 5, 56, 22, 210351, tzinfo=utc), verbose_name='开始时间'),
        ),
    ]
