export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_SUCCESS_SAFE = 'LOGIN_USER_SUCCESS_SAFE';
export const LOGIN_USER_SUCCESS_UNSAFE = 'LOGIN_USER_SUCCESS_UNSAFE';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';


export const USER = {'Student': 1, 'Teacher': 2, 'Staff': 3, 'Admin': 4};