# Generated by Django 2.0.3 on 2018-05-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180504_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='user_id',
            new_name='uid',
        ),
    ]
