# Generated by Django 2.0.3 on 2018-05-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180531_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='create_time',
            new_name='date',
        ),
    ]
