# Generated by Django 2.0.3 on 2018-05-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180527_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='uid',
            new_name='user',
        ),
    ]
