# Generated by Django 2.0 on 2018-06-04 08:04

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='section',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, storage=forum.models.MediaFileSystemStorage(), upload_to=forum.models.media_file_name),
        ),
        migrations.AddField(
            model_name='announcement',
            name='md5sum',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
