# Generated by Django 2.0.3 on 2018-05-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180531_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
