# Generated by Django 2.0 on 2018-06-04 08:09

from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180604_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='md5sum',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='thread',
        ),
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='forum.Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='forum.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='md5sum',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, storage=forum.models.MediaFileSystemStorage(), upload_to=forum.models.media_file_name),
        ),
    ]
