# Generated by Django 2.0.3 on 2018-06-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180531_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(default='default-section', max_length=50),
        ),
    ]
