export const BACKEND_SERVER_URL = "http://10.180.31.226:8000/";

export const BACKEND_API = {
    get_token: 'api/info/get_token',
    get_user: 'api/info/user',
    get_major: 'api/info/major/',
    get_department: 'api/info/department/',
    get_course: 'api/info/course/',
    get_course_faculty: 'api/info/course_faculty',
    get_log: 'api/info/log/',
    search_faculty: 'api/info/faculty/',
    register_student: 'api/info/register_student',
    register_faculty: 'api/info/register_faculty',
    register_staff: 'api/info/register_staff',
    register_course: 'api/info/register_course',
    get_staff_info: 'api/info/staff/',
    get_student_info: 'api/info/student/',
    get_faculty_info: 'api/info/faculty/',
    get_admin_info: 'api/info/admin/',
    update_password: 'api/info/update_password',
    batch_add_student: 'api/info/batch_student',
    batch_add_faculty: 'api/info/batch_faculty',
    batch_add_staff: 'api/info/batch_staff',
    upload_image: 'api/info/upload_image',
};

export const DEBUG_API = {
    get_token: 'api/get_token',
    get_user: 'api/user',
    get_major: 'api/major/',
    get_department: 'api/department/',
    get_course: 'api/course/',
    get_course_faculty: 'api/course_faculty',
    get_log: 'api/log/',
    search_faculty: 'api/faculty/',
    register_student: 'api/register_student',
    register_faculty: 'api/register_faculty',
    register_staff: 'api/register_staff',
    register_course: 'api/register_course',
    get_staff_info: 'api/staff/',
    get_student_info: 'api/student/',
    get_faculty_info: 'api/faculty/',
    get_admin_info: 'api/admin/',
    update_password: 'api/update_password',
    batch_add_student: 'api/batch_student',
    batch_add_faculty: 'api/batch_faculty',
    batch_add_staff: 'api/batch_staff',
    upload_image: 'api/upload_image',

};